# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='logo.jpg', upload_to=''),
        ),
    ]
